In [403]:
import numpy as np  
import pandas as pd 
#importing modules.. to see graphical analyiss, see the earliest file

In [404]:
df=pd.read_csv('USA_Housing.csv')
#reading data

In [405]:
df.head()

Avg. Area Income  Avg. Area House Age  Avg. Area Number of Rooms  \
0      79545.458574             5.682861                   7.009188   
1      79248.642455             6.002900                   6.730821   
2      61287.067179             5.865890                   8.512727   
3      63345.240046             7.188236                   5.586729   
4      59982.197226             5.040555                   7.839388   

   Avg. Area Number of Bedrooms  Area Population         Price  \
0                          4.09     23086.800503  1.059034e+06   
1                          3.09     40173.072174  1.505891e+06   
2                          5.13     36882.159400  1.058988e+06   
3                          3.26     34310.242831  1.260617e+06   
4                          4.23     26354.109472  6.309435e+05   

                                             Address  
0  208 Michael Ferry Apt. 674\nLaurabury, NE 3701...  
1  188 Johnson Views Suite 079\nLake Kathleen, CA...  
2  9127 Elizabeth Stravenue\nDanieltown, WI 06482...  
3                          USS Barnett\nFPO AP 44820  
4                         USNS Raymond\nFPO AE 09386

In [406]:
df=df.drop('Address',axis=1)
#dropping address column

In [407]:
df.head()
#head of data

Avg. Area Income  Avg. Area House Age  Avg. Area Number of Rooms  \
0      79545.458574             5.682861                   7.009188   
1      79248.642455             6.002900                   6.730821   
2      61287.067179             5.865890                   8.512727   
3      63345.240046             7.188236                   5.586729   
4      59982.197226             5.040555                   7.839388   

   Avg. Area Number of Bedrooms  Area Population         Price  
0                          4.09     23086.800503  1.059034e+06  
1                          3.09     40173.072174  1.505891e+06  
2                          5.13     36882.159400  1.058988e+06  
3                          3.26     34310.242831  1.260617e+06  
4                          4.23     26354.109472  6.309435e+05

In [408]:
train, validate, test = \
              np.split(df.sample(frac=1, random_state=42), 
                       [int(.7*len(df)), int(.8*len(df))])
                       #splitting data

In [409]:
train.shape

(3500, 6)

In [410]:
validate.shape

(500, 6)

In [411]:
test.shape

(1000, 6)

In [412]:
def scaler(x):
    return ((x-x.mean(axis=0))/(x.max(axis=0)-x.min(axis=0)))

In [413]:
X_train=train.drop('Price',axis=1)
X_validation=validate.drop('Price',axis=1)
X_test=test.drop('Price',axis=1)
y_train=train[['Price']]
y_validation=validate[['Price']]
y_test=test[['Price']]
#defining data

In [414]:
X_train=scaler(X_train)
X_validation=scaler(X_validation)
X_test=scaler(X_test)
#scaling data

In [415]:
X_train.insert(0,'bias',value=1)
X_validation.insert(0,'bias',value=1)
X_test.insert(0,'bias',value=1)
#inserting bias column

In [416]:
def normality(x,y):
    z1=np.dot(x.T,x)
    z1=np.linalg.pinv(z1)
    z2=np.dot(x.T,y)
    lam=0.0001
    f=np.eye(z1.shape[1])
    f[0,0]=0
    z1=z1+f
    total=np.dot(z1,z2)
    theta=total
    return theta
    #normal equation

In [417]:
theta=normality(X_train,y_train)
#weight matrix

In [418]:
pre=np.dot(X_validation,theta)
#predictions for validation set

In [419]:
pre=pd.DataFrame(pre)

In [420]:
correct = [1 if abs(a-b)<500000 else 0 for (a, b) in zip(pre.iloc[:,0], y_validation.iloc[:,0])]
accuracy = (sum(map(int, correct)) / float(len(correct)))
print ('accuracy = {0}%'.format(accuracy * 100))
#accuracy for validation set

accuracy = 1.2%


In [421]:
theta

array([[1.23514352e+06],
       [1.16004365e+08],
       [8.54049926e+07],
       [5.66172286e+07],
       [5.74305640e+07],
       [6.98241610e+07]])

In [422]:
#as you can see accuracy is pretty lower, this is because theta, (weight matrix) is pretty high, so we need to decrease the weight. This can be done by scaling again, as weight depends on X (feature matrix). 
# So let's try it

In [423]:
X_train.iloc[:,1:]=scaler(X_train.iloc[:,1:])
X_validation.iloc[:,1:]=scaler(X_validation.iloc[:,1:])
X_test.iloc[:,1:]=scaler(X_test.iloc[:,1:])

In [424]:
X_train.head()

bias  Avg. Area Income  Avg. Area House Age  Avg. Area Number of Rooms  \
1501     1         -0.094013             0.163352                  -0.073005   
2586     1         -0.159864             0.143778                  -0.009034   
2653     1          0.020884             0.120492                  -0.043456   
1055     1          0.008760             0.050630                   0.117510   
705      1          0.059732            -0.403059                  -0.065851   

      Avg. Area Number of Bedrooms  Area Population  
1501                     -0.161885         0.110012  
2586                     -0.188552         0.104800  
2653                     -0.437441        -0.100503  
1055                      0.067004        -0.169171  
705                      -0.332996         0.207932

In [425]:
theta=normality(X_train,y_train)

In [426]:
pre=np.dot(X_validation,theta)

In [427]:
pre=pd.DataFrame(pre)

In [428]:
theta

array([[1.23514352e+06],
       [1.16004365e+08],
       [8.54049926e+07],
       [5.66172286e+07],
       [5.74305640e+07],
       [6.98241610e+07]])

In [429]:
correct = [1 if abs(a-b)<500000 else 0 for (a, b) in zip(pre.iloc[:,0], y_validation.iloc[:,0])]
accuracy = (sum(map(int, correct)) / float(len(correct)))
print ('accuracy = {0}%'.format(accuracy * 100))

accuracy = 1.2%


In [430]:
# koi farak nahi pada, so let's try to use square root of features, to lower theta(weight matrix)

In [431]:
X_train=np.sqrt(abs(X_train))
X_validation=np.sqrt(abs(X_validation))
X_test=np.sqrt(abs(X_validation))

In [432]:
X_train.head()

bias  Avg. Area Income  Avg. Area House Age  Avg. Area Number of Rooms  \
1501   1.0          0.306615             0.404168                   0.270194   
2586   1.0          0.399830             0.379181                   0.095049   
2653   1.0          0.144511             0.347120                   0.208460   
1055   1.0          0.093596             0.225011                   0.342798   
705    1.0          0.244401             0.634869                   0.256614   

      Avg. Area Number of Bedrooms  Area Population  
1501                      0.402349         0.331680  
2586                      0.434225         0.323728  
2653                      0.661393         0.317022  
1055                      0.258851         0.411305  
705                       0.577058         0.455995

In [433]:
theta=normality(X_train,y_train)

In [434]:
theta=theta**1/2048

In [435]:
pre=np.dot(X_validation,theta)

In [436]:
pre=pd.DataFrame(pre)

In [437]:
theta

array([[5.91072940e+02],
       [6.66470082e+05],
       [6.86455061e+05],
       [6.34718129e+05],
       [9.38762258e+05],
       [6.57296702e+05]])

In [438]:
correct = [1 if abs(a-b)<500000 else 0 for (a, b) in zip(pre.iloc[:,0], y_validation.iloc[:,0])]
accuracy = (sum(map(int, correct)) / float(len(correct)))
print ('accuracy = {0}%'.format(accuracy * 100))

accuracy = 76.8%


In [439]:
# so now, it is giving slightly good answer, but we have to scale down too much

In [440]:
prediction=np.dot(X_test,theta)

In [441]:
prediction=pd.DataFrame(prediction)

In [442]:
correct = [1 if abs(a-b)<500000 else 0 for (a, b) in zip(pre.iloc[:,0], y_validation.iloc[:,0])]
accuracy = (sum(map(int, correct)) / float(len(correct)))
print ('accuracy = {0}%'.format(accuracy * 100))

accuracy = 76.8%


In [ ]:
#test set accuracy